### ISSUE TITLE
etcd comparison

### ISSUE THREAD

**Issue by nonpcnpc** [prologic/bitcask#100]
How does this project compare to etcd that uses wal+bbolt?

**Comment by prologic** [comment]
[etcd](https://etcd.io) is a:

> A distributed, reliable key-value store for the most critical data of a distributed system

[Bitcask](https://github.com/prologic/bitcask) (_at least this Go library implemtnation_) is only an embedded key/value store following the same fundamental design principles of the original [paper](https://riak.com/assets/bitcask-intro.pdf?source=post_page---------------------------)

So to answer your question; bitcask and etcd are _not_ comparable.

If you are after a distributed version of bitcask I recommend you look at the sister project [bitraft](https://github.com/prologic/bitraft) which uses this library and raft to build a distributed key/value store with configurable levels of consistency.

**Comment by jsign** [comment]
Just to add more info: BBolt underlying design is a B+Tree, so that's kind of another class of design compared to LSM. 
Both have kind of an opposite tradeoff regarding reading and write throughput and maybe optimal conditions of HD type (spinning disk or SSD).

**Comment by prologic** [comment]
Yeah that's correct. Bitcask (_this library_) pretty much follows the original Bitcask design paper. It uses a Write-Ahead-Log (_WAL_) that is used to write all changes sequentially to disk. This is known as the "active datafile". It is rotated once its maximum configured size has been reached into a read-only datafile where only reads occur.

Only the keyspace itself (_just the keys_) are held in memory and the only difference we've (_recently_) made in this library is the use of an Adaptive Radix Tree which more or less has the same performance as a hash table anyway but also supports in-order traversal of keys and prefix scans (_so you get the best of several features_). This effectively means the size of your database is only constrained by two things:

- Memory and the total no. of keys (_keyspace_)
- Disk space and the total size of all key/value pairs including old changes (_if not merged_)

The "Merge" part of LSM in this library (_and the original paper_) is controlled by the end-user. You get to decide when you want to merge old datafiles and compact them removing old key/value pairs that have changed and deleting ones that no longer exist.

Trade-offs :) I'd like to think there are many good use-cases for this database design however and especially this particular library written inGo. So we're very interested in supporting and helping new users and new use-cases!

**Comment by nonpcnpc** [comment]
So how does bitcask compare with badger then?
Assuming etcd with badger backend, how would bitraft compare to it?
In other words, what does this library bring to the table? I am not really versed in storage engines so I'm just curious why and where I should use bitcask/bitraft over established libraries/projects?

**Comment by jsign** [comment]
Most storage engines make a decision in the tradeoff between read and write throughput.

In bitcask, writes are very fast because the amount of work you should do to comply with the action is minimal. That preference has storage costs, merging costs of compaction, and memory limitations. 

In other engines you mention, they might prefer to make reads faster than writes to optimize for other use-cases, or because want more memory limit flexibility.

All these are in a theoretical POV discussion. You also have optimizations at the implementation level, because there are many things that matter in the real world besides some theoretical design.

I hope this helps to shed more light on your question.

**Comment by nonpcnpc** [comment]
Great, thanks for the info(especially about the fast writes). I'm looking for some benchmark comparisons though :)

**Comment by prologic** [comment]
@nonpcnpc We also regularly do benchmarks against other storage engines. See: https://github.com/prologic/bitcask-bench

**Comment by nonpcnpc** [comment]
Something's VERY wrong with your badger data(comparing with bbolt)...hence I don'trust the rest of it.

**Comment by prologic** [comment]
@nonpcnpc 

> Something's VERY wrong with your badger data(comparing with bbolt)...hence I don'trust the rest of it.

Care to share what you believe is wrong about the benchmark comparisons?

Please note that [bitcask-bench](https://github.com/prologic/bitcask-bench) is actually a fork of [pogreb-bench](https://github.com/akrylysov/pogreb-bench) so we (_as in I mostly at this point_) have made zero attempt at anything close to "real-world" comparisons of the various engines.

Like all benchmarks -- Take them with a grain of salt. They are "contrived" at best and not refelctive of real-world performance. They serve mostly as a useful guide as to whether or not you've improved or degraded raw performance by making change X over change Y.
