### ISSUE TITLE
Recovery from crashes

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#104]
With #78 now done we have a pretty comprehensive way to doo full integrity checks on the entire database and potentially "recovery" from corruption.

Just some further thoughts on this as I was poking back around at the original papaer the [Riak's docs](https://docs.riak.com/riak/kv/2.1.4/setup/planning/backend/bitcask/index.html#bitcask-s-strengths)

Specifically:

> * **Fast, bounded crash recovery**
>
> Crash recovery is easy and fast with Bitcask because Bitcask files are append only and write once. The only items that may be lost are partially written records at the tail of the last file that was opened for writes. Recovery operations need to review only the last record or two written and verify CRC data to ensure that the data is consistent.

This leads me to believe we _should_ be able to automatically reco ver from crashes by inspecting the last N items in the "active datafile" for correctness/integrity? We could automatically recover from such failures and put the "bad data" aside for the operator to inspect. Thoughts?

**Comment by jsign** [comment]
May be a good idea, yes.

Getting the last N elements from the datafile I'm not sure is possible because te encoding is forward only biased.

The index can be used, but that will add a further assumption: the index file isn't corrupted.

The least amount of assumptions I getting those last N entries by only reading the current datafile from start. Am I missing something maybe?

**Comment by prologic** [comment]
Without going and looking at the Risk codebase (_and I don't think the original paper spelled out how this works in great detail_); I _think_ would be as simple as:

- `db, _ := bitcask.Open("/path/to/db", ...)
  - internally read the active datafile in full (_assume inactive datafiles are "okay"_)
  - if we reach a reach a bad record; discard the remaining entries (_assumes only one or two_)

This only works iif all previous entries have been fsync'd to disk and only the last N partially failed in some way.

I _would_ only enable this behaviour with some kind of `WithAutoRecovery()` option or something.

Otherwise the default would be to bail out and let the use run recovery tools?

What do you think?

**Comment by jsign** [comment]
That seems fine. I like what you mention initially of moving bad data apart and not loosing it. Maybe manual inspection could make an educated guess to recover it later.

**Comment by prologic** [comment]
Yeah it really depends on how badly the last N (_one or two_) entries were written/flushed to disk (_if at all_) and frankly this is as good as you can get data integrity without fsync'ing on every write (_which we have an option for_) but degrades write performance significantly (_possibly only useful by those that want 100.00% of writes to persist to disk guaranteed_)
