### ISSUE TITLE
Gomobile

### ISSUE THREAD

**Issue by joeblew99** [prologic/bitcask#107]
Thanks for this.

I plan to use this on mobile.
I doubt anyone has tried it yet.

Data types will be protobufs to allow version evolution. Like if one mobile is at V1 and another mobile is at V2.

Then the raft version on a global cluster. Sort of like an etcd. Sort of curious if the bitraft system will cope with many data centers ?

What do think think ?

**Comment by prologic** [comment]
Hello jow! Thanks for your interest in the Go [Bitcask](https://github.com/prologic/bitcask) library! Happy to have you!

> Sort of curious if the bitraft system will cope with many data centers ?

I assume you are referring th the sister project [Bitraft](https://github.com/prologic/bitraft)? If so it uses a Redis-like protocol with the [Finn](https://github.com/tidwall/finn) library which also means the Raft transport/protocol is also Redis-like. Finn is quite fast and I use the `finn.FastLog` backend.

To answer your question more directly though; I don't know :) - If you have access to such Infra I'd been very happy to help you scale this up. Bare in mind however that Bitraft as it currently stands is just an example of building a distributed key/value store atop Bitcask itself. Bitcask is where I primarily spend most of my efforts/focus on making it a very robust and performant key/value embedded store with predictable latency.

If you do end up using the Bitraft as an example to key off; I'd imagine you'd want to explore multi-raft or some kind of sharding scheme to split your data over multiple data centers / regions as you horizontally scale out.


Hope this helps  :)
