### ISSUE TITLE
Do we support or want to support Go 1.12.x?

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#111]
Noticed in #110 that we are using [Go 1.13 Error Wrapping](https://blog.golang.org/go1.13-errors) features of `fmt.Errorf()` -- specifically the `%s` format specifier.

Do we want to continue to support Go 1.12.x or drop it?

/cc @jsign who wrote that code :)

**Comment by jsign** [comment]
I think we should stick to the last Go version, at least with minor versions. Which makes also coherence with benchmark results (not only affected by code but the compiler version).

**Comment by prologic** [comment]
So you're okay with only supporting Go 1.13+ from here on?

**Comment by jsign** [comment]
Yep
