### ISSUE TITLE
Readonly mode?

### ISSUE THREAD

**Issue by farwydi** [prologic/bitcask#112]
Hello, is it possible to use storage in readonly mode?
This will allow use rsync and achieve scalability.

**Comment by prologic** [comment]
Some notion of "read only" mode came up once before in #79 - Some attempts were made at a PR but it was abandoned.

> is it possible to use storage in readonly mode?

What do you mean by "storage here?

> This will allow use rsync and achieve scalability.

What and How will `rsync` be used here to scale a bitcask db?

Have you also seen the sister project [Bitraft](https://github.com/prologic/bitraft)?

**Comment by farwydi** [comment]
> What do you mean by "storage here?

https://github.com/prologic/bitcask/blob/803b08949ec76de545fe9026cc55ac6f8187f389/bitcask.go#L416

> What and How will rsync be used here to scale a bitcask db?

More slave and one master.
Master - write/read.
Slave - read.
Slave use `rsync` to sync with master.
Read requests are balanced between slaves.

Prerequisites: I am developing a service (file system) that uses KV storage for indexing (links to real files are stored there)
The idea was: Create more replicas of this service and use it in read-only mode (like master/**slave** postgres)

> Some notion of "read only" mode came up once before in #79 - Some attempts were made at a PR but it was abandoned.

It seems that this question has already been raised. I'm not sure, but can `rsync` crash the database over time?

**Comment by prologic** [comment]
Hmmm.... So is `path` here is a read-only filesystem in your view?

The whole notion of master/slave doesn't fit well with thd design of bitcask as it is. I'm still a bit fuzzy on this based on your description.

**Comment by farwydi** [comment]
Here is my vision, is this correct or is it impossible in principle?
```go
package main

import (
	"bytes"
	"crypto/rand"
	"github.com/google/uuid"
	"github.com/prologic/bitcask"
	"log"
	"os/exec"
	"time"
)

func writeMode() {
	db, err := bitcask.Open("bitcask")
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		if err := db.Close(); err != nil {
			log.Fatal(err)
		}
	}()

	u, err := uuid.Parse("4de92675-67aa-475f-b526-d9d6b49b2062")
	if err != nil {
		log.Fatal(err)
	}
	buf := []byte(`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec ex purus. Suspendisse potenti. Vivamus lectus leo, luctus in semper eget, vulputate a quam. Maecenas a dolor tempor, porttitor quam ut, pharetra lectus. Nam auctor tortor et ex auctor, vel congue metus convallis. Etiam dictum justo eu velit tempor, et maximus massa ullamcorper. Donec at quam et orci condimentum sodales. Nunc dignissim, ex et pellentesque eleifend, libero leo suscipit mauris, ac mollis urna purus vehicula lacus. In nec nulla sed lorem hendrerit pulvinar. Morbi aliquam libero at massa malesuada, eget consequat sapien euismod.`)
	for {
		log.Println("Write")
		err = db.Put(u[:], buf)
		if err != nil {
			log.Fatal(err)
		}

		time.Sleep(time.Second)

		u = uuid.New()
		_, err = rand.Read(buf)
		if err != nil {
			log.Fatal(err)
		}
	}
}

func readMode() {
	db, err := bitcask.Open("bitcask_rsync")
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		if err := db.Close(); err != nil {
			log.Fatal(err)
		}
	}()

	u, err := uuid.Parse("4de92675-67aa-475f-b526-d9d6b49b2062")
	if err != nil {
		log.Fatal(err)
	}
	buf := []byte(`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec ex purus. Suspendisse potenti. Vivamus lectus leo, luctus in semper eget, vulputate a quam. Maecenas a dolor tempor, porttitor quam ut, pharetra lectus. Nam auctor tortor et ex auctor, vel congue metus convallis. Etiam dictum justo eu velit tempor, et maximus massa ullamcorper. Donec at quam et orci condimentum sodales. Nunc dignissim, ex et pellentesque eleifend, libero leo suscipit mauris, ac mollis urna purus vehicula lacus. In nec nulla sed lorem hendrerit pulvinar. Morbi aliquam libero at massa malesuada, eget consequat sapien euismod.`)

	for {
		log.Println("Read")
		d, err := db.Get(u[:])
		if err != nil {
			log.Fatal(err)
		}

		if !bytes.Equal(d, buf) {
			log.Fatal("crash")
		}

		time.Sleep(time.Millisecond * 500)
	}
}

func main() {
	go writeMode()
	go readMode()

	go func() {
		t := time.NewTicker(2* time.Second)
		for range t.C {
			cmd := exec.Command(
				"rsync",
				"-rtv",
				"bitcask/",
				"bitcask_rsync",
			)
			err := cmd.Run()
			if err != nil {
				log.Fatal(err)
			}
			log.Println("Sync")
		}
	}()

	select {}
}
```

Now there is a error
```
$ rsync -rtv bitcask/ bitcask_rsync
sending incremental file list
000000000.data
rsync: rename "...bitcask_rsync/.000000000.data.hl1PNL" -> "000000000.data": Permission denied (13)

sent 94,345 bytes  received 185 bytes  189,060.00 bytes/sec
total size is 94,253  speedup is 1.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

**Comment by prologic** [comment]
Oh wow! Yeah I see where you're going with this but this won't work for several reasons. I'm happy to help you come up with a more viable solution though :)

So you're basically opening two Bitcaks databases here on different filesystems. One that's read-only and the other that's read/write. Rsync'ing from one to the other won't really work here in any online scenario since Bitcask won't notice the "new" or "modified" files out-of-band like this.

Can you help me understand what you're trying to achieve here in some high-level description? If you're goal is to have a sharded Bitcask db over multiple nodes; that is possible with some work.

**Comment by farwydi** [comment]
What about:

```go
db, _ := bitcask.Open("bitcask_rsync")
db.Block()
// rsync here
db.Unblock()
```
When blocking active read/write not available
When readonly active write not available

Or:
```go
db, _ := bitcask.Open("bitcask_rsync")
db.Reload(func() error {
    // rsync here
})
```
Mutex reading/writing
And reopen active file descriptors

**Comment by prologic** [comment]
This library already embed the `sync.RWMutex` struct; so you _could_ just call `db.Lock()` perform your r'sync; then reopen the db. Unfortunately though `Bitcask.reopen()` isn't currently exported and used internally by `.Merge()` -- We could export it though; or you could just call `db.Close()` and `db = bitcask.Open(...)` again after your `.Unlock()`?

**Comment by farwydi** [comment]
I understand :) Yes this is what I need after syncing, the database is not updated and I need to call the `reopen` method, but it is closed.

I can try to do PR, how do you look at it?

**Comment by prologic** [comment]
Put up a PR and let's discuss there :)

**Comment by farwydi** [comment]
https://github.com/prologic/bitcask/pull/113
