### ISSUE TITLE
funding warning/error

### ISSUE THREAD

**Issue by jsign** [prologic/bitcask#114]
The `Sponsor` button shows an error/warning about the user not being currently enrolled (which I assume maybe is on the waitlist). 
I'm also on the wailist, mostly to push other users (like @prologic ) in the section of: _users you'd like to sponsor and can't yet_ ;)

**Comment by prologic** [comment]
So here's the thing; This whole "Sponser" an OSS Project seems to be the all the rave these days :D 

Problem is a) I've never bothered to get into this and b) I don't know how to set it up

I'm actually off the waitlist now; but haven't setup my profile -- I'm stuck on what tiers to setup :)

**Comment by jsign** [comment]
I don't know much about setting up funding options, besides imagining some reasonable way of how they work. I think that just deleting the `github:` would do the trick to avoid the red box message (and only leave your patreon account).

I hope Github get up to speed to accept more users, since: i) I found it better since you don't only sponsor someone but also show the badger to let others know who you found (and help to fund further), ii) if you enroll before 2020 (or something similar) Github will pair donations (so double). iii) Seems to charge no (or tiny) fees compared to Patreon.

**Comment by prologic** [comment]
I do quite like the Github sponsors programme too. The thing I'm stuck on is setting up tiers in my profile. The way I see it is this; if you or someone sponders one of my OSS projects for say $1/month it's just a nice gesture to say thank you really and show support. Beyond that I have no idea what are reasonable tier levels. I've looked at a few other's on Github sponsors that are also off the waitlist and all setup and so far found similar profiles of $1/month with similar blurb/opinion as above and $5/month

**Comment by jsign** [comment]
1, 5, 25, 50, 250? 
Seems to cover any case, but pretty hard to create some descriptions for high tiers, yes :)

**Comment by jsign** [comment]
1, 5,  and 15 seems reasonable, to cover most cases.
For people expecting to work full time on something real, more tiers up to $250 for companies or similar isn't crazy.

**Comment by prologic** [comment]
I'll complete my profile tonight and cmoe up with something reasonable :)

**Comment by prologic** [comment]
Finally got around to setting this up properly. Once approved I can close this :)

**Comment by prologic** [comment]
>You've been approved for GitHub Sponsors
>
> Approved and ready to go! Your GitHub Sponsors profile is now live.
> A note from GitHub:
>
>> We're thrilled to have you in the program! Thank you for being an early user of GitHub Sponsors, and thanks even more for your amazing open source contributions. -- Devon and the whole GitHub >> Sponsors team 💖
