### ISSUE TITLE
Error mmap: closed

### ISSUE THREAD

**Issue by dgallion1** [prologic/bitcask#132]
Running on Windows10 after about a week I see these errors.
Any ideas?

```
 mmap: closed
 read db\000000001.data: file already closed
```

```
func GetHistory(db *bitcask.Bitcask) [][]byte {
	hist := make([][]byte, 0, 10)
	db.Scan([]byte(statusPrefix), func(key []byte) error {
		dta, err := db.Get(key)
		if err != nil {
			logIt.Errorf("ErrorDb %v", err)
			return nil // <-- Could this be the issue?
		}
		hist = append(hist, dta)
		return nil
	})
	return hist
}

```

**Comment by prologic** [comment]
Do you have more logs available?

Can you share anything more about your code, usage, environment? I'm sure this is a bug, but I need a little more to help track this down. Unfortunately I don't have access to a Windows machine to dev and test on so I will need your help!

**Comment by dgallion1** [comment]
The logs are application-related other than what I shared.
I'll try to narrow it down. This could take a while.
This db.Merge() code could be related.

```
go func() {
		for {
			db.Merge()
			time.Sleep(time.Hour * 1)
		}
	}()
```


Thanks.

**Comment by dgallion1** [comment]
This code without the locking will deadlock.
It appears that all operations must stop during the merge?

```
func main() {
    db, _ := bitcask.Open("db")
	defer db.Close()
	var lk sync.Mutex

	go func() {
		for {
			lk.Lock()
			db.Merge()
			lk.Unlock()
			time.Sleep(time.Millisecond)
			//time.Sleep(time.Hour * 1)
		}
	}()

	for{
		lk.Lock()
		db.Put([]byte("Hello"), []byte("World"))
		val, _ := db.Get([]byte("Hello"))
		db.Put([]byte("Hello"), val)
		lk.Unlock()
	}
}

```

**Comment by dgallion1** [comment]
I modified Merge() with b.mu.Lock() at the begining.
Made this work by creating no lock versions of the required functions. PutNoLock()...
It's running.

**Comment by prologic** [comment]
To answer your question; yes you the database must be locked currently for a merge operation to take place. I'm hoping to fix this in #108 and #109  -- If you'd like to help refactor this code I'd greatly appreciate it! Merging really should (_and it was at some point_) lock-free and shouldn't rewrite the entire database or touch the active datafile.

**Comment by prologic** [comment]
For a bit of background into why it got changed is #compact is #76 I believe where the old algorithm wasn't compacting the database for deleting keys than span across datafiles.

**Comment by dgallion1** [comment]
Read file xx.data
Looking up each item read, if the returned item's fileID isn't xx.data, move on.
If it is in xx.data, write the item back to the database.
Remove xx.data
Move to the next xx1.data and repeat

**Comment by prologic** [comment]
Can you put up a PR?
