### ISSUE TITLE
Error if open a existing db folder in windows env

### ISSUE THREAD

**Issue by xapanyun** [prologic/bitcask#14]
Hi, bitcask works very well in Linux env, but I encounted a issue in windows, if the db folder alread existing, Open("my.db") will get "file is accessing by other process" issue, I debuged bitcask and noticed the error is hanppen in bitcask.go line 305 "err = os.Rename(tempdf.Name(), df.Name())".

So I changed (df *Datafile) Close() method both to below and it works:
```
if df.w != nil{
		err = df.w.Close()
	}

	if err == nil && df.r != nil{
		df.r.Close()
	}

	if err == nil && df.ra != nil{
		df.ra.Close()
	}

	return
```

My question is do you think the fixing is OK?

**Comment by prologic** [comment]
Hi @xapanyun Thanks for your interest in [this Bitcask](https://github.com/prologic/bitcask) implementation! Much appreciated.

To answer your question;

> My question is do you think the fixing is OK?

Short answer is; I don't know. I do not have access to Windows machines to do development or testing on; so I'd need your help here! I'm more than happy to ensure that the test suite runs on Windows machines in CI and publish Windows binaries too! -- Probably file that as a separate Issue and PR.

However to your original problem:

> file is accessing by other process

When and under what circumstances do you receive this error? The reason I ask is that once a `bitcask.Open("/path/to/db")` has been called; we create a lock for that path preventing other processes from potentially clobbering files. This is done [here](https://github.com/prologic/bitcask/blob/master/bitcask.go#L420) and released [here](https://github.com/prologic/bitcask/blob/master/bitcask.go#L61) and uses [this library](https://github.com/gofrs/flock) (_which is suppose to be cross platform!_).

Also I would encourage you to put up an actual PR against this issue so we can discuss and review your code changes more precisely :) It helps a lot to see an actual diff against existing code.

**Comment by prologic** [comment]
In fact; let me ask this differently...

Are you expecting to be able to open the same database from multiple processes?

**Comment by xapanyun** [comment]
> In fact; let me ask this differently...
> 
> Are you expecting to be able to open the same database from multiple processes?

No, I received this error in following case:
1. Run my program firstly, it will create my.db folder normaly.
2. Close my program and restart it again, I will receive this error.

And I can sure the error is threw by Os.Remame during Merge method, and the root cause is your close method didn't close all the file handle. Since my fixing will make it works, but I'm not sure why don't you close all handle.

**Comment by xapanyun** [comment]
BTW, I will submmit a PR later.

**Comment by prologic** [comment]
> And I can sure the error is threw by Os.Remame during Merge method, and the root cause is your close method didn't close all the file handle. Since my fixing will make it works, but I'm not sure why don't you close all handle.

Ahh that makes sense. And yeah what you describe is definitely a bug in that case. Please put up a PR and let's get it merged! Thank you :)

**Comment by xapanyun** [comment]
Ok, but I don't know why it works in Linux env, since I have both Linux and Windows, it seems works in Linux, I also did some research, maybe It is related to the behavior of Os.Rename.

**Comment by prologic** [comment]
Yeah good question; `os.Rename()` likely behaves differently on Windows than on Linux. I'm not 100% sure to be honest. Taking a syscall trace would highlight the differences between the two OSes but I have no idea how to do that on Windows :D

Its probably a good idea to ensure the previously open file descriptor is closed anyway before the rename.
