### ISSUE TITLE
Corrupt index

### ISSUE THREAD

**Issue by kanendosei** [prologic/bitcask#143]
For whatever reason, when a program crash occurs, the `index` file becomes corrupt and any attempt to reconnect to the bitcask datastore hangs until the index is removed, at which point, obvious problems ensue.

Is there a way to cleanly rebuild the index on startup?

**Comment by prologic** [comment]
This should be part of #104 and I would love to see this implemented! As you've no doubt seen just removing the corrupt indices (_purely for performance reasons_) is enough as they get rebuilt anyway. Are you willing to put up a PR?

**Comment by kanendosei** [comment]
When I remove the corrupt index, it doesn't get rebuilt. I end up having issues where the code gives me errors because the key isn't found.

**Comment by prologic** [comment]
Issues during the time window when the index is corrupted?
The key/value is there though after you rebuild the index right?

**Comment by kanendosei** [comment]
To reproduce:

1. Run application which panics while bitcask is open
2. Try to restart application
3. Application hangs on db.Open
4. Close application
5. Remove Index
6. Application runs, but none of the keys exist with either getkeys or with a direct lookup ("Key not found" errors).

Is there some command I'm missing which rebuilds the index?

**Comment by prologic** [comment]
I will look into this pronto! THank you for the very clear repro. There is `bitcask recover` CLI tool but I'm not sure how much help that would be at the moment. Let me try to exercise your repro and fix this :)

**Comment by kanendosei** [comment]
Fix outside this code:

Remove index.
Run `bitcask recover -p "path_to_files"`

Then, you have to run something to rebuild the index.
`bitcask keys -p "path_to_files"`

Once the application restarts, the index appears to be correct again.

**Comment by prologic** [comment]
Sorry been rather busy with my day job and haven't actually found some spare time to look at this yet. But if you put up a PR I would be willing to review it!
