### ISSUE TITLE
How to use a url as key?

### ISSUE THREAD

**Issue by xiaozhuai** [prologic/bitcask#164]
I try to put a key-value which the key is a url.
But that seems not working.
What should I do?

**Comment by xiaozhuai** [comment]
It was max key size, I enlarge it, and now works

**Comment by prologic** [comment]
Cool glad you figured it out! I was going to ask if you were getting any errors :) But yes key sizes must be limited to some degree, allowing them to be of undefined length is problematic for performance and memory optimisation reasons. Set an appropriate `MaxKeySize` for your use-case.
