### ISSUE TITLE
Race condition on file lock

### ISSUE THREAD

**Issue by LeGEC** [prologic/bitcask#165]
The following way to release the file lock :

[bitcask.go:89](https://github.com/prologic/bitcask/blob/afdf956e7aa194ec6ab32a59be164556a589ca17/bitcask.go#L89) :

```go
func (b *Bitcask) Close() error {
	defer func() {
		b.Flock.Unlock()
		os.Remove(b.Flock.Path())
	}()
        ...
```

Is not safe and leads to race conditions between other actors trying to acquire the lock.

---

Currently, the lock action consists in :

1. a opening a file (an getting a file handle)
2. placing a `flock` on that handle

and unlocking consists in :

3. releasing the flock
4. deleting the file from disk

action 1. gives a handle *on the inode pointed at* when this action is run, action 4. unlinks the file from the file system *but does not necessarily delete the inode*.

Here is a race scenario :

```text
# process 1 'owns' the lock on `/tmp/lock`, process 2 and process 3 want to grab that lock :
| process 1    | process 1      | process 3
               1. open /tmp/lock,
               get handle on inode A
2. release lock
               3. get flock on handle
               works because inode A is now lock free
4. unlink /tmp/lock from filesystem (rm /tmp/lock)
/tmp/lock no longer points at inode A
                                5. open file /tmp/lock
                                new file is created with inode B
                                6. take lock on handle
                                works, because inode B is lock free

Bug : now both process 2 and process 3 think they have 'the' lock
```

note : the use of `inode` is partially incorrect, as flocks are probably associated with a file object, but the above highlights the issue : two processes can hold a lock to something that was named `/tmp/lock` at some point, but which are actually two different objects.

**Comment by LeGEC** [comment]
See an example of failing test here :

https://github.com/LeGEC/bitcask/blob/gv/issue-165-unlock-race-condition/lock_test.go

**Comment by LeGEC** [comment]
The code has a logical bug, which does not depend on the platform,

however : the "flock" implementation depends on the platform, and I only tested it on linux.

**Comment by LeGEC** [comment]
I see two ways to fix the issue :

1. call os.Remove() without calling Flock.Unlock()
2. calling Flock.Unlock() without calling os.Remove()

2. would change the behavior : instead of disappearing, the "lock" file would remain even when the database is unlocked.

1. would require to fix the locking too : if you hold a filehandle on a file which is removed from disk, you should take care in replacing the filehandle ; `gofrs/lock` does not seem to offer a convenient way to do this through its public api.

**Comment by prologic** [comment]
Thanks for your very detailed report!

I'm. not so keen on changing behaviour re 2) but open to it.

Re 1) I'm not sure sure I follow, especially this part:

> if you hold a filehandle on a file which is removed from disk, you should take care in replacing it with a fresh filehandle ; gofrs/lock does not seem to offer a convenient way to do this through its public api.

Also in your OP can you describe the racy behaviour here in more details? If you close the database you would expect the lock to be released. The need to remove the "lockfile" can be discussed of course.

I'd be interested to see an actual failing test; do you have a test run of https://github.com/LeGEC/bitcask/blob/gv/issue-165-unlock-race-condition/lock_test.go ?

**Comment by LeGEC** [comment]
Hi

Here is a sample output :

```text
$ go test . -run TestLock
--- FAIL: TestLock (0.17s)
    lock_test.go:91: [runner 14] lockCounter was > 1 on  5 occasions, max seen value was  2
    lock_test.go:91: [runner 03] lockCounter was > 1 on  2 occasions, max seen value was  3
    lock_test.go:91: [runner 02] lockCounter was > 1 on  3 occasions, max seen value was  3
    lock_test.go:91: [runner 00] lockCounter was > 1 on  1 occasions, max seen value was  2
    lock_test.go:91: [runner 12] lockCounter was > 1 on  7 occasions, max seen value was  3
    lock_test.go:91: [runner 01] lockCounter was > 1 on  8 occasions, max seen value was  2
    lock_test.go:91: [runner 04] lockCounter was > 1 on  6 occasions, max seen value was  4
    lock_test.go:91: [runner 13] lockCounter was > 1 on  1 occasions, max seen value was  2
    lock_test.go:91: [runner 17] lockCounter was > 1 on  4 occasions, max seen value was  2
    lock_test.go:91: [runner 10] lockCounter was > 1 on  3 occasions, max seen value was  2
    lock_test.go:91: [runner 08] lockCounter was > 1 on  6 occasions, max seen value was  2
    lock_test.go:91: [runner 09] lockCounter was > 1 on  4 occasions, max seen value was  2
    lock_test.go:91: [runner 05] lockCounter was > 1 on  1 occasions, max seen value was  2
    lock_test.go:91: [runner 19] lockCounter was > 1 on  3 occasions, max seen value was  3
    lock_test.go:91: [runner 07] lockCounter was > 1 on  4 occasions, max seen value was  3
    lock_test.go:91: [runner 11] lockCounter was > 1 on  9 occasions, max seen value was  2
    lock_test.go:91: [runner 15] lockCounter was > 1 on  1 occasions, max seen value was  3
    lock_test.go:91: [runner 16] lockCounter was > 1 on  1 occasions, max seen value was  3
FAIL
FAIL	github.com/prologic/bitcask	0.176s
FAIL
```

(I copied it in the [commit message](https://github.com/LeGEC/bitcask/commit/fc5580d10efa45e3c0d337f8d8e761b86b16a254), not the best place to make an information visible ... :wink: )

**Comment by LeGEC** [comment]
About the "fresh file handle" : if the lock action consists in :

1. a opening a file (an getting a file handle)
2. placing a `flock` on that handle

and unlocking consists in :

3. deleting the file from disk
4. releasing the flock

action 1. gives a handle *on the inode pointed at* when this action is run, action 3. deletes the file *but not necessarily the inode*.

Here is a race scenario :

```text
# process 1 'owns' the lock on `/tmp/lock`, process 2 and process 3 want to grab that lock :
| process 1    | process 1      | process 3
               1. open /tmp/lock,
               get handle on inode A
2. remove /tmp/lock from disk
/tmp/lock no longer points at inode A
3. release lock
               4. get flock on handle
               works because inode A is now lock free
                                5. open file /tmp/lock
                                new file is created with inode B
                                6. take lock on handle
                                works, because inode is lock free

Bug : now both process 2 and process 3 think they have 'the' lock
```

note : the use of `inode` is partially incorrect, as flocks are probably associated with a file object, but the above highlights the issue.

The fix in this case is : after acquiring the lock, make sure tha `/tmp/lock` still exists on disk, and that its inode is the same as the one of the file handle.

**Comment by LeGEC** [comment]
If we try to fix the above by running "3. delte the file from disk", and not running "4. releasing the flock", the race scenario above will not take place (which is a good thing :) ). I don't see a race scenario in this case, and I think it is a possible fix for the bug.

But poor process 2 would have no chance to run for "gaining the lock" if it repeatedly tries to acquire it through the file handle he opened in the beginning (inode A would stay locked, until it is collected by the the system).

It would be better to close the handle, and reopen `/tmp/lock` on each retry. However, I don't see an immediate, convenient way to do this through `gofrs/lock` current public API.

**Comment by prologic** [comment]
Damnit this pesky racy bug you've found is a hard one :)

I need some time to _think_ about this in more detail when I can actually sit down and think more deeply.

I am however open to any valid ideas/suggestions you have to fix this properly. Even if that involves swapping out the library used for file locking or writing our own. You seem to know a lot more about this than I do -- which is a good thing! (_can't be experts in everything!_). So if you are able and willing any PR(s) that fix this good and proper will be highly appreciative and valuable to all users of Bitcask here (_that no. is apparently growing!_).

**Comment by LeGEC** [comment]
Since `*flock.Flock` is an anonymous field of your `Bitcask` struct, this makes the interface of `flock.Flock` part of the interface of `Bitcask`. So technically, breaking the interface of `flock.Flock` would be a breaking change for your library.

I would need more context on how you use `bitcask` in your other projects :

* do you need/want to support windows ? or are you only running this library on linux servers ? (the way you can lock files on both platforms is actually very different)
* you always use flock as an exclusive lock (you never use `flock.RLock()` functionnality, in all your use cases flock ensures that one single process only can access the underlying data files). Is that correct ?
* (minor) you only call the non blocking `flock.TryLock()` variant of flock (you never use `flock.Lock()`). Is that correct ?

**Comment by prologic** [comment]
> do you need/want to support windows ? or are you only running this library on linux servers ? (the way you can lock files on both platforms is actually very different)

No. Primarily Linux -- And mostly in containers (_if that matters_).

> you always use flock as an exclusive lock (you never use flock.RLock() functionnality, in all your use cases flock ensures that one single process only can access the underlying data files). Is that correct ?

Yes this is correct. Technically here is no reason another process _cannot_ open the database in read-only mode and read the index and datafile(s); however it __must absoultely not__ open the current WAL or attempt to touch or write to it, etc in any way.

So we _could_ use the non-exclusive lock for read-only operations. Just not something any of us that use Bitcask have bothered to build at this point...

> (minor) you only call the non blocking flock.TryLock() variant of flock (you never use flock.Lock()). Is that correct ?

This one I'm not even sure why we do this nor do I remember. 🤷‍♂️

**Comment by prologic** [comment]
@LeGEC Wondering whether you'll be able to find the time to implement the fix you've described here? I _think_ this is important to solve and #171 will need this!

**Comment by LeGEC** [comment]
Hi,

Regarding #171 : I think it will be quite some work to have a ReadWrite lock working, especially if you look at the guarantees you want to have on the files on disk.

From what I see : the pain point would be around the `index` file.

Since the `data` files are append only : it should be doable to take advantage of this to get a copy of the data, and re-build the index afterwards.

**Comment by prologic** [comment]
Yeah the index can be rebuilt.

I'd love it if you helped fix this race condition/bug re locking though. Then I can probably work on getting g #171 done ;)

**Comment by LeGEC** [comment]
Hi, I submitted a Pull Request for this issue.

Of course, you are welcome to comment the proposed fix.
This first proposed fix only offers a simple lock (not a RWlock), and assumes it is ok to delete the locked file when releasing the lock.

This matches the current behavior of bitcask, but may not be ok for other usages (such as managing a RWLock behavior).

**Comment by prologic** [comment]
Thank you! I will review this over the next coming day!

**Comment by prologic** [comment]
The PR was merged. Closing
