### ISSUE TITLE
TTL Support

### ISSUE THREAD

**Issue by codenoid** [prologic/bitcask#168]
item expiration

**Comment by prologic** [comment]
Hello! 👋 What's your use-case for TTL of keys? I'm curious; I don't have one myself in any of my applications that use Bitcask, but you clearly do!

Of course this _can_ also be done at the "application level" too I suppose. But let's discuss!

**Comment by codenoid** [comment]
just like another, redis, badger, it is really useful for developer when their database has item/documient expiration, idk if it used for expiring something (like Subscription), but in my case i use it for github.com/codenoid/file.io

**Comment by prologic** [comment]
I can see I'd want something like this for expiring persistent sessions. I'm open to a PR or two for this, do you have any considerations for designing/implementation this?

**Comment by yashschandra** [comment]
@prologic i am trying to implement this feature, however need to discuss some things to move further:
1. How to change our storage data model, should we introduce a set of flags which can tell whether ttl is set for a key or not?
2. Should we consider ttl value as *time.Time in internal.Item?
3. I am considering checking if a key has expired or not only at the time of its access.

PS: doing open source first time so need some guidance 🙂

**Comment by prologic** [comment]
Hi 👋 No worries about first time contributing to an open-sources project! Here to help!

Regarding where to store this effective TTL value or timestamp, don't you mean [Entry](https://pkg.go.dev/github.com/prologic/bitcask@v0.3.6/internal#Entry)? `Item` is used to hold the location on disk of a key/value pair, where `Entry` is what is encoded on disk.

In any case, Hmmm good question!

I _think_ storing the TTL/Timeestamp as part of the encoded on-disk structure `Entry` makes sense personally and is validated on read. This is similar to the design of Tombstone values as well. This way no performance is affected. You will probably want to return a new error type to indicate the key expired as opposed to it doesn't exist. After you notice the key is expired you might also want to write it back at that point with a Toombstone / null value so a later `Merge()` operation can compact the database.

**Comment by yashschandra** [comment]
@prologic can we discuss [this](https://github.com/prologic/bitcask/pull/177) ?

**Comment by prologic** [comment]
Yes of course! Pick a medium 😁

**Comment by yashschandra** [comment]
I am not sure where to have long design/refactor discussions but comment section on that pr works for me. You have any other medium in mind?

**Comment by prologic** [comment]
I'm available to chat with on Signal if you use that, or you can also email me. But the original issue is also fine, I use Github App on my phone now so I'm a bit more active than I used to be.

**Comment by prologic** [comment]
Didn't you put up a PR for this already? 😁

**Comment by yashschandra** [comment]
#177

**Comment by yashschandra** [comment]
@prologic this can be closed
