### ISSUE TITLE
Live Backups

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#171]
We have `bitcask export|import` tooling but what we don't have (_yet_) is a way to do a live export/dump/backup of the running database that may be locked by a process.

#165 is related here and _should_ be solved first; after-which we need to add the capability of opening a Bitcask DB in read-only mode.

**Comment by prologic** [comment]
I _could be wrong_ but I believe #175 makes this possible now.

**Comment by yashschandra** [comment]
Hi @prologic if you could suggest in more detail what's needed to be done here, I can do it in next few days.

**Comment by prologic** [comment]
Hmmm good question! I've not tried to take a backup of a live running application using Bitcask yet... But N offline `rsync` works rather nicely.

What are you thinking here?

**Comment by yashschandra** [comment]
_rsync_ should work fine.

**Comment by prologic** [comment]
And in fact it does work quite nicely. The only downside in practice that I found is that I've had to stop the application running with an active open Bitcask database. I haven't quite figured out why yet but I suspect it's because some of the index is still in memory and hasn't been persistent to disk yet, which if is the case then we need away on start hope to be validate the index?￼￼￼

**Comment by yashschandra** [comment]
Do you remember the exact issue you faced?

**Comment by prologic** [comment]
Not exactly, I have to find some time to reproduce the behaviorist. I believe the problem is twofold; a) the in-memory index (key space) is only synced to disk when you call `.Sync()` b) On database open we don't have a way to see if the  `index` on disk is out-of-date (say due to a crash or termination without sync)

**Comment by prologic** [comment]
Ideally we would detect that the l on disk index is stale and rebuild it.￼

**Comment by yashschandra** [comment]
for b., we can have a **meta.json** file (besides config.json) which can store these flag durably.
eg. When a put method is called - store flag _index_up_to_date_ as "false", whenever sync happens, change this flag to "true"

**Comment by yashschandra** [comment]
For live backup of _index_ file, we can check if the flag set is false, start rebuilding _new_index_ file in background, when this operation is finished replace old file with new one. Any issues you see in this approach ?

**Comment by prologic** [comment]
The problem with doing this is that you incur a lot of disk I/O when you reopen a database. If we can find a way to determine whether the index is stale without having to reread all datafiles that would be great￼￼

**Comment by yashschandra** [comment]
Potentially we can save some json metadata regarding opened database. This metabase can include a flag - _index_up_to_date_. We can set this flag on every index sync and unset after every put (since we don't immediately sync index)

**Comment by prologic** [comment]
That might work

**Comment by yashschandra** [comment]
Any golang rsync library in mind? I am thinking of using [this](https://github.com/Redundancy/go-sync)

**Comment by prologic** [comment]
I've been looking at various rsync libraries actually in our discussions. I hadn't found anything that "quite" fit. Let me have a look at what you found...

What are you thinking here now?

**Comment by prologic** [comment]
Oooh that library looks really interesting and well put together! I didn't come across that one in my findings.

**Comment by yashschandra** [comment]
Only thing due to which I don't think this package is not good for us is that it offers so much more than what we need. Most of it's things will not be used by us 😄

**Comment by prologic** [comment]
Yeah agreed. Thinking about the solution you came up with of storing a flag, I'm trying to find a way where we can adapt that solution a bit to use some kind of cryptographic hashes. Haven't _thought_ this quite through yet, but ideally if we could store a hash of the known keyspace as it was before we terminated with someone we can compare to on disk. Then we have something that can potentially tell us if the index on disk is stale.

Not sure of the details yet...

**Comment by yashschandra** [comment]
I came up with this - 

`
func (b *Bitcask) Put(key, value []byte) error {
	...
	b.trie.Insert(key, item)
	if !b.metadata.IndexOutOfDate {
		b.metadata.IndexOutOfDate = true
		// handle error
		b.metadata.Save(filepath.Join(b.path, "metadata.json")) // persist metadata file
	}

	return nil
}

func (b *Bitcask) Close() error {
	...

	if err := b.saveIndex(); err != nil {
		return err
	}

	...
}

func (b *Bitcask) saveIndex() error {
	if err := b.indexer.Save(b.trie, filepath.Join(b.path, "index")); err != nil {
		return err
	}
	if !b.metadata.IndexOutOfDate {
		return nil
	}
	b.metadata.IndexOutOfDate = false
	return b.metadata.Save(filepath.Join(b.path, "metadata.json")) // persist
}

`

**Comment by yashschandra** [comment]
I feel that In most of the cases index on disk will be stale because DB will have more "put" than "close"

**Comment by yashschandra** [comment]
To make things faster, we can think as suggested in #108

**Comment by prologic** [comment]
Hmmm I think we're missing something here... I'll answer after some TV but I have an idea that could work! It's a combination of your original idea plus a better way to persist the index on disk to reduce the need to rescan all datafiles

**Comment by prologic** [comment]
So this is how I _think_ we can fix this situation.

- Everytime we rotate the active datafile out, we also sync the index to disk.

When we open an existing database we replay the active datafile to "resync" the index we loaded from disk. If there is no on-disk index, we resort to rescanning all datafiles.

This _should_ mean in most cases we only have to rescan one active datafile when opening an existing database. The upside is that you won't loose any key/value pairs as both the active datafile (a write-ahead log) and index will always be in sync so your view of the database will be consistent.

What do you think?

**Comment by yashschandra** [comment]
syncing index to disk takes N disk writes (since we end up writing for all keys to disk again). I think index per datafile will be more performant (to sync index, we will require to write on disk fewer times). Thoughts?

**Comment by prologic** [comment]
Couple of things, the index is just writing the art (adaptive radix tree used). It is a single write, but it is an O(n) iteration over the keyspace.

See: https://github.com/prologic/bitcask/blob/master/internal/index/codec_index.go

Trying to keep an index per datafile would not fit within the model I don't believe.

**Comment by yashschandra** [comment]
I am just worried about O(n) iteration over the keyspace. If number of keys is large, then iterating over all keys can add significant overhead. But yeah, this works and we can benchmark it.

**Comment by yashschandra** [comment]
@prologic can close this issue

**Comment by prologic** [comment]
> @prologic can close this issue

This is done, as-in we can take live backups now? How does this work? Remind me :)

**Comment by prologic** [comment]
Oh wow! I can't believe I missed this! Awesome work! 🚀
