### ISSUE TITLE
Reasons for os.FileMode 0755 and 0640 on directory and cache files, respectively?

### ISSUE THREAD

**Issue by stensonb** [prologic/bitcask#181]
Hi there!  I love the simplicity of this.  Can you shed light on the details of why these file permissions were chosen:

https://github.com/prologic/bitcask/blob/master/bitcask.go#L420
https://github.com/prologic/bitcask/blob/master/internal/data/datafile.go#L62

I think defaulting to 0700 and 0600 makes sense, but I'm sure that'll break someone else's use case.

Any thoughts of an API to set these?

**Comment by stensonb** [comment]
> if possible please also make sure your Bug Report or Feature Request is clearly defined
> with either examples or a reprodicible case (_if a bug_).

:)

FYI - "if" should be capitalized, and reprodicible should be spelled reproducible.

**Comment by prologic** [comment]
I think a PR to fix this is in order! Call it a force of habit (bad habit?)

**Comment by stensonb** [comment]
Submitted as #183   :)

**Comment by prologic** [comment]
I think this can be closed 😁
