### ISSUE TITLE
How to run YCSB workload for bitcask? 

### ISSUE THREAD

**Issue by pentium3** [prologic/bitcask#186]
Are there any ways to run YCSB workload for bitcask?

**Comment by prologic** [comment]
Soddy for the naivety but what is YCSB?￼

**Comment by pentium3** [comment]
> Soddy for the naivety but what is YCSB?￼

a benchmark tool for key-value store    https://github.com/brianfrankcooper/YCSB

**Comment by prologic** [comment]
None of these seem to target in a better database whose primary is is still in bed in another application as a library. Also I'm not touching Java or maven with a 10 foot pole 😂

Is there something in particular you're looking for in terms of performance that the benchmark on the README doesn't answer?￼￼

**Comment by pentium3** [comment]
Just want to compare different kv stores under the same type of workload..

**Comment by prologic** [comment]
Yeah I get that, but those benchmarks (YSCB) are not comparing the right thing. If you want to compare embedded key/value stores, have a look at [this](https://github.com/prologic/bitcask-bench)

**Comment by prologic** [comment]
But as you've not described what your workload is I'm not sure how else I can help?

**Comment by prologic** [comment]
I'm closing this as invalid as I don't believe the benchmark fits Bitcask
