### ISSUE TITLE
Providing more information in Stats

### ISSUE THREAD

**Issue by yashschandra** [prologic/bitcask#188]
Currently `Stats` looks like - 

```
type Stats struct {
	Datafiles int
	Keys      int
	Size      int64
}
```

Would like to add some details related to how much extra space can be saved by performing merge.

New `Stats` can potentially be - 

```
type Stats struct {
	Datafiles int
	Keys      int
	Size      int64
        Reclaimable int64 // how much data on disk is useless now, eg. key overridden
}
```

Use case - Can decide on the fly if I should/need to trigger `Merge`

**Comment by prologic** [comment]
I like it! How shall we implement this ?

**Comment by yashschandra** [comment]
We already save size of `Entry` for each key in index. We can store `Reclaimable` into a field in `Bitcask, then whenever we do a `put` we check if key already exist and if yes, then add size of existing `Entry` to `Reclaimable` and resume normal put operation (ie. append in WAL and update index).

We can think of storing `Reclaimable` into a meta object (like we created in [this pr](https://github.com/prologic/bitcask/pull/185/files)) so that it can be durably saved and used upon repoen. What do you think?

**Comment by prologic** [comment]
I like this approach! Are you able to PR this?

**Comment by yashschandra** [comment]
Do you have plans/time to merge #185  anytime soon? Metadata implementation is already done here.

**Comment by prologic** [comment]
Done

**Comment by yashschandra** [comment]
#189 resolves this
