### ISSUE TITLE
Save metadata to disk in background

### ISSUE THREAD

**Issue by yashschandra** [prologic/bitcask#190]
We have a field `ReclaimableSpace` in `metadata` that can be pretty dynamic, just thinking of regularly saving it to disk asynchronously (currently it is being saved only when db is closed) so that even in case of crash we can have fair estimate of this value. Right now in face of a crash, this value is not corrected until next merge process (which makes it 0)

**Comment by prologic** [comment]
Typically in many of my applications that use Bitcask I call `.Sync()` periodically which flushes all data to disk. We _could_ tie that into there?

**Comment by yashschandra** [comment]
@prologic I think we can mark it another "good first issue"

**Comment by prologic** [comment]
Good idea!

**Comment by Hassall** [comment]
> 
> 
> Typically in many of my applications that use Bitcask I call `.Sync()` periodically which flushes all data to disk. We _could_ tie that into there?

In that case wouldn't the contents of the metadata on disk always be the same? (index: true, reclaimablespace: 0)

Perhaps the metadata update to disk can be configurable (for every n puts? all puts?)
