### ISSUE TITLE
Evict inactive keys from memory to disk to conserve memory

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#193]
As your database grows, some proportion of keys can potentially become infrequently used or inactive, depending on your use-case and access patterns.

Instead of holding the entire key space in memory at all times, what if we evict infrequently or inactive keys to disk?

**Comment by Kleissner** [comment]
Yeah I just tried bitcask out for storing a couple of billion records and I'm frankly disappointed.
Only couple of hundred million records in and it requires 46 GB on disk (OK) and 47 GB in memory (!) - NOT ok.

What's up with all these key-value databases that require more RAM than disk storage? Why people have NO memory management development skills anymore? I guess that's the only bad thing with Go, it abstracts memory management too much. It's a shame, SQL databases can store TBs of data no problem and don't require equal amount of RAM.

**Comment by prologic** [comment]
> Yeah I just tried bitcask out for storing a couple of billion records and I'm frankly disappointed.
> 
> Only couple of hundred million records in and it requires 46 GB on disk (OK) and 47 GB in memory (!) - NOT ok.
> 
> 
> 
> What's up with all these key-value databases that require more RAM than disk storage? Why people have NO memory management development skills anymore? I guess that's the only bad thing with Go, it abstracts memory management too much. It's a shame, SQL databases can store TBs of data no problem and don't require equal amount of RAM.

Your comments and feedback are frankly rude and borderline aggressive!

Did you want to try again before I decide to help you?

Ref a little human decency and courtesy...

**Comment by Kleissner** [comment]
My comment is indeed frank and I didn't mean to come over as rude. I'm happy you developed this database and I'm sure many people find it useful and that's a good thing.
For my particular use case (storing billions of records) it appears to be no fit unfortunately.

**Comment by prologic** [comment]
Yeah it is not simply because the key space is held in memory. This is by design and won't suit your use case sorry 😥

FWIW I spent considerable time optimizing memory usage of the trie used to hold keys but it's constraint is key space and memory.

**Comment by prologic** [comment]
Bitcask is designed to be very fast not to store billions of keys unfortunately. Based on the description of your requirements you would roughly require over 128 GB of memory to store just to key space of your data sets assuming the default 64 bytes per key. 

Storage of actual values however is unconstrained.￼￼

**Comment by prologic** [comment]
I will update the documentation to make this more clear sorry for the miscommunication￼

**Comment by yashschandra** [comment]
Do you have any trie based approach in mind? SSTables seems like a good candidate (harder to implement)

**Comment by prologic** [comment]
Not familiar with SsTable

**Comment by yashschandra** [comment]
Basically you store all keys on disk in sorted order and keep a subset of it in memory eg. every 10th key from sorted order (which will again be sorted in memory).

So this way to search a key, you perform binary search in memory, find the appropriate "slot" and then traverse on disk (max checking 10 records) and get your key. Advantage - number of keys in memory is slashed to 1/10th

**Comment by prologic** [comment]
It distracts a lot from the original Bitcask paper but hmmmm

**Comment by yashschandra** [comment]
Any resource/idea you found interesting for this?

> It distracts a lot from the original Bitcask paper but hmmmm

Bitcask follows unordered LSM trees implementation, SSTables follow ordered LSM tree implementation

**Comment by prologic** [comment]
I mean the [original paper](https://riak.com/assets/bitcask-intro.pdf?source=post_page---------------------------) that this library implements...  

I'm not sure, I'd have to read up carefully on SSTables to see if its worthwhile.
