### ISSUE TITLE
Background process to clear expired keys

### ISSUE THREAD

**Issue by yashschandra** [prologic/bitcask#203]
Since we support TTL on keys (which deletes a key lazy manner), we can think of having a background process which can delete those keys periodically, interval can be configurable.

Advantage - 
1. Deleted keys will be removed from RAM

Disadvantages - 
1. More disk space required now (as we will be proactively putting tombstone values on disk)
2. Performance hit because of extra processing

**Comment by prologic** [comment]
I feel like this should just be an API call leaving it up to the application to do it automatically if desired

**Comment by yashschandra** [comment]
Do we want to introduce another data structure (min heap is suitable) for storing keys with TTL? That will be efficient that doing brute force ie. `Fold` on every key and do a `get` 🙄

**Comment by prologic** [comment]
Explain how this would work?

**Comment by yashschandra** [comment]
Heap approach - 

1. If key is put with a TTL, store it and add it to a priority queue (min heap)
2. When Cleanup (need to come up with a better name) is called, extract from front of the PQ (front key will have least TTL), check if TTL has passed and if yes then delete it. Keep on doing it for next front elements until we get a key whose TTL has not passed. Then stop.

We did not traverse the whole trie, rather just keys in order of their TTLs

**Comment by prologic** [comment]
I see. Worse case we store 2x the no. of keys if all your keys are stored with TTL(s)?

**Comment by yashschandra** [comment]
yes

**Comment by prologic** [comment]
Seems reasonable to me, it's a trade off really.

**Comment by yashschandra** [comment]
Now that I think of it, min heap approach is complex to implement. 

1. Updation of TTL -
    a. At time t, set x with TTL t+5
    b. At time t+1, set x with TTL t+10
    To update an element, we will require to have pointers to the location of keys in the heap

2. Saving/retrieving min heap from disk -
    a. We will always have to take care of keeping our PQ on disk up to date with PQ in memory

Redis uses a different [approach](https://redis.io/commands/expire#how-redis-expires-keys) that looks easy to implement. @prologic @Hassall what do you guys think?

**Comment by prologic** [comment]
Looks like a reasonable approach actually.

**Comment by Hassall** [comment]
@yashschandra 

https://github.com/bluele/gcache

I used this to implement my LFU. It can also be used with a time interval to evict elements. Simply override the evict function to self delete.
