### ISSUE TITLE
How to atomically batch set keys in bitcask?

### ISSUE THREAD

**Issue by remuscl** [prologic/bitcask#211]
> A Batch is a sequence of Sets, Merges, Deletes, and/or DeleteRanges that are applied atomically.

-- https://pkg.go.dev/github.com/cockroachdb/pebble#Batch

Bitcask is a wonderfully open-source project. Thanks very much for your great contribution!

**Comment by yashschandra** [comment]
@remuscl are you asking about batched operations (something similar to DB transactions)?

@prologic correct me if i am wrong, we don't provide any api to perform multiple operations atomically so far. Could be a great addition.

**Comment by prologic** [comment]
That's right we don't at the moment ... I've personally never needed the feature myself

**Comment by yashschandra** [comment]
@prologic should we consider implementing it? I have one idea which we can discuss for atomic inserts

**Comment by yashschandra** [comment]
Idea is to create a transaction log for current active file.
Eg. we want to insert (foo:bar, bar:baz, hello:world) <- these 3 key value pairs atomically
Step 1 - attach 1 transaction id to all 3 pairs, let's say transaction id is "txn1"
Step 2 - Start appending 3 entries
Step 3 - insert "txn1" to a transaction log

Failure scenario -

latest datafile - [(key1:value1,txn0)(foo:bar, txn1), (bar:baz,txn1)XXXX]
transaction log (only required for latest datafile) - [(txn0)]

Now if step 2 fails in between (eg. we were not able to write hello:world), we will not have "txn1" in transaction log. So upon restart, we can check last active file, verify if transaction id attached to each key value pair is present in transaction log or not. In the above example, we can discard all records after (key1:value1,txn0)

Once a datafile is closed, we can delete/truncate existing transaction log file and create new 1 for new datafile

We do similar thing in case of index also.

**Comment by prologic** [comment]
Seems reasonable to me

How do we handle rollback in a live sense without restart ?

**Comment by yashschandra** [comment]
> How do we handle rollback in a live sense without restart ?

I think this scenario can come only when we successfully wrote in datafile but failed to write in transaction log file.  

We can store transaction id in our index (in memory) as well. This means index will always point to the latest successful insert.

**Comment by prologic** [comment]
Hmmm I'm not convinced (yet)...

What if we do it without a "transaction log" and just keep a pointer to the current position in the active datafile. Then create a in-memory struct to batch multiple operations together, serialise that in one go, write it in one go. If any part of that fails mid-way through we just truncate the active datafile to the last position. If this succeeds we update the position. We can store the current position in the index but it probably doesn't need to persist to disk?

I have to admit I'm getting a but confused between "batching" and "atomicity". Which are we designing/implementing here? Batching or Transactions or both? :D

**Comment by yashschandra** [comment]
> What if we do it without a "transaction log" and just keep a pointer to the current position in the active datafile. Then create a in-memory struct to batch multiple operations together, serialise that in one go, write it in one go. If any part of that fails mid-way through we just truncate the active datafile to the last position. If this succeeds we update the position. We can store the current position in the index but it probably doesn't need to persist to disk?

This is a good approach, much simpler to implement. One corner case -
when we are batching multiple writes together and writing them in one go, if process fails in between and system restarts, it is possible that some of the keys were written but not all. If we don't persist latest location on disk, is there any other way we can find out till what location we have to truncate the file?

> I have to admit I'm getting a but confused between "batching" and "atomicity". Which are we designing/implementing here? Batching or Transactions or both? :D

I started the conversation with "atomicity" in mind, ie. we want a group of writes to happen together (or not 😛 )

**Comment by prologic** [comment]
> This is a good approach, much simpler to implement. One corner case -
> when we are batching multiple writes together and writing them in one go, if process fails in between and system restarts, it is possible that some of the keys were written but not all. If we don't persist latest location on disk, is there any other way we can find out till what location we have to truncate the file?

This is a good point. We _should_ probably persist the last active datafile position to the index on-disk **before** doing the batch operations.

**Comment by prologic** [comment]
> I started the conversation with "atomicity" in mind, ie. we want a group of writes to happen together (or not 😛 )

Yeah I _think_ as long as we define it this way, it'll be fine. I need to go look up the differences again between "batching" and "transactions" (_if there are any?_)
