### ISSUE TITLE
search in 000000.data found same key

### ISSUE THREAD

**Issue by xiusin** [prologic/bitcask#217]
![image](https://user-images.githubusercontent.com/36065131/120751635-eecb2d80-c53a-11eb-963e-16e159139efa.png)

As shown in the figure, I show the search results in a new line

**Comment by prologic** [comment]
Hi @xiusin 👋

I'm not sure what I'm looking at here? How did you produce this picture? What tool are you using here?

It is expected you'll see the same key multiple times in datafiles until a merge operation is done. This is normal behavior.

Kind regards

**Comment by xiusin** [comment]
sublime， I'll take a look at the documentation

**Comment by prologic** [comment]
Let me know if you have any issues or questions 🙇‍♂️
