### ISSUE TITLE
Old duplicate keys are not pruned across rotated Datafiles

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#27]
```
        --- PASS: TestMergeOpen/Setup/Close (0.02s)
    bitcask_test.go:353:
        	Error Trace:	bitcask_test.go:353
        	Error:      	Should be true
        	Test:       	TestMergeOpen
    --- PASS: TestMergeOpen/Merge (17.77s)
        --- PASS: TestMergeOpen/Merge/Merge (8.80s)
        --- PASS: TestMergeOpen/Merge/Open (8.95s)
        --- PASS: TestMergeOpen/Merge/Get (0.00s)
        --- PASS: TestMergeOpen/Merge/Close (0.02s)
FAIL
FAIL	github.com/prologic/bitcask	40.020s
```

**Comment by prologic** [comment]
So I'm not entirely convinced there's a bug here with the original behavior;

I basically ran this bit of shell:

```#!sh
$ while true; do for i in $(seq 0 10); do bitcask -d -p ./tmp.db set "$i" "FWtnOOHAjbD6rNxWWEeVOCj7JXSEPGJQ"; done; ls -lah ./tmp.db/; du -s -h ./tmp.db/; done
```

And as you can see the old datafiles that get rotated out are definately compacted down:

```#!sh
$ ls -lah tmp.db/
total 100K
drwxr-xr-x 28 prologic staff  896 Jul 25 21:43 .
drwxr-xr-x 24 prologic staff  768 Jul 25 21:40 ..
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000000.data
-rw-r--r--  1 prologic staff  158 Jul 25 21:43 000000000.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000001.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000001.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000002.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000002.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000003.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000003.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000004.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000004.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000005.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000005.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000006.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000006.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000007.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000007.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000008.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000008.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000009.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000009.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000010.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000010.hint
-rw-r-----  1 prologic staff  590 Jul 25 21:43 000000011.data
-rw-r--r--  1 prologic staff  180 Jul 25 21:43 000000011.hint
-rw-r-----  1 prologic staff 3.0K Jul 25 21:43 000000012.data
drwx------  2 prologic staff   64 Jul 25 21:43 merge072566264
```

**Comment by prologic** [comment]
Once thing I have found however (_hard to write a test for_) is that old keys that span across data files won't be compacted. This would have to be some kind of "pruning" process to do this efficiently I think.

**Comment by prologic** [comment]
Can you confirm my tests? I'm wondering whether you're seeing old keys across data files not being pruned -- Merging seems to work; I'm not finding a direct bug here so far.

**Comment by prologic** [comment]
So I wrote a `Prune()` API.

Here's before and after:

```
prologic@Jamess-MacBook
Thu Jul 25 23:29:05
~/Projects/bitcask
 (fix_broken_merge) 0
$ bitcask -p ./tmp.db stats
{
  "Datafiles": 18,
  "Keys": 11,
  "Size": 15438
}

prologic@Jamess-MacBook
Thu Jul 25 23:29:09
~/Projects/bitcask
 (fix_broken_merge) 0
$ bitcask -p ./tmp.db prune

prologic@Jamess-MacBook
Thu Jul 25 23:29:12
~/Projects/bitcask
 (fix_broken_merge) 0
$ bitcask -p ./tmp.db stats
{
  "Datafiles": 18,
  "Keys": 11,
  "Size": 4180
}
```

**Comment by prologic** [comment]
If you'd like to play with this; the branch is [fix_broken_merge](https://github.com/prologic/bitcask/tree/fix_broken_merge)

I still don't think `Merge()` is broken however; but rather that old duplicate  keys across rotated datafiles are never pruned. `Pune()` does this now.

Needs a bit of cleaning up (_the code_) but otherwise could probably get merged.

Maybe combine `Merge()` and `Prune()` into a single function/operation? I'm not sure :)

**Comment by awnumar** [comment]
Interesting, I had assumed Merge would just do that itself.

I notice that the number of data files stays constant also after running prune. Perhaps if we're adding a Prune command, make it more powerful by making it remove duplicates, compact database down into the smallest number of files, etc. Then it can stay separate from the Merge command, as that one is called on every single Open so it shouldn't be too slow.

What is Merge's actual purpose though, as clearly as possible? I might be misunderstanding.

**Comment by awnumar** [comment]
I think this also means that Merge's documentation is inaccurate as it claims to re-claim disk space. Also the force flag should be better explained there too.

**Comment by awnumar** [comment]
Some quick tests with the branch you pushed,

- `Put` is a lot slower.
- `Open` takes noticeably longer.
- The second time I run the program it fails with `too many open files`.

**Comment by prologic** [comment]
> What is Merge's actual purpose though, as clearly as possible? I might be misunderstanding.

Originally when I read the paper; I read the merge operation to mean; collapsing duplicate keys and tomstome values in old rotated datafiles and creating hint files for faster load times on startup.

I could be mis-read the paper though or maybe missed some important aspect of merging.

**Comment by prologic** [comment]
> I think this also means that Merge's documentation is inaccurate as it claims to re-claim disk 
space
 
It does but only in a limited  way I guess?

> Also the force flag should be better explained there too.

Agreed.

**Comment by prologic** [comment]
> Some quick tests with the branch you pushed,
> 
> * `Put` is a lot slower.
> * `Open` takes noticeably longer.
> * The second time I run the program it fails with `too many open files`.

Is that with my branch unmodified? I added some logging which isn't great for performance that I'll remove now I understand the problem more. I also changed the default max datafile size just for testing; I should change that back.

**Comment by prologic** [comment]
> I notice that the number of data files stays constant also after running prune. Perhaps if we're adding a Prune command, make it more powerful by making it remove duplicates, compact database down into the smallest number of files, etc. Then it can stay separate from the Merge command, as that one is called on every single Open so it shouldn't be too slow.

I _think_ with some careful coding `Merge()` and `Prune()` _could_ be combined.

I'm open to ideas though!

**Comment by awnumar** [comment]
> Is that with my branch unmodified? I added some logging which isn't great for performance that I'll remove now I understand the problem more. I also changed the default max datafile size just for testing; I should change that back.

That could be it.

**Comment by prologic** [comment]
* cleaned up the code just now and force-pushed that branch. And put up PR #28 which partially solves the lack of pruning problem described here. Let me know what you think after testing this? We have a few routes we can go down and important decisions to make :)

**Comment by prologic** [comment]
So... Where are we at with this? I had a half day at work today so I can get back to you unless you've made significant progress towards what we discussed/
