### ISSUE TITLE
Acknowledging contributors

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#39]
I would like to acknowledge contributors to this project beyond just what Github keeps around as "metadata".

What is the currently accepted / conventional way to do this for OSS projects? Add to [README](/README.md)? Add a new file?

I'd especially like input from @awnumar @muesli and @jsign as recent significant contributors. Of course all current contributors (_even just single commits fixing typos/etc!_) will be acknowledged :)

Please provide comments/feedback on the best way to handle this.

----

> I follow quite a few other OSS projects I find interesting and also contribute myself where I can. Of particular note is the discussion that occurred in muesli/beehive#207 ([started from this comment](https://github.com/muesli/beehive/pull/207#issuecomment-517955956)) 😂
Admittedly I _think_ the conversation went a little sideways; but it did spark my own thoughts and the desire to _correctly_ acknowledge all those that have contributed to [prologic/bitcaks](https://github.com/prologic/bitcaks) thus far 😀

**Comment by awnumar** [comment]
Perhaps an [AUTHORS](https://github.com/awnumar/memguard/blob/master/AUTHORS) file?

**Comment by prologic** [comment]
Sounds fine to me.

**Comment by muesli** [comment]
As I've stated in the issue you referenced, I think `AUTHORS` files are pretty pointless these days. They're usually not up-to-date, have no indication who's responsible for what part of code and who's still regularly contributing. The repository itself and platforms like GitHub provide a lot more accurate and meaningful information in that regard. That said, as a "thank you" to everyone involved they're still fine, of course :wink:

**Comment by prologic** [comment]
I do agree of course; an `AUTHORS` file loses quite a bit of information. But yes perhaps the contents should be reworded to say "Thank you ..." Happy to hear other suggestions! Not married to an `AUTHORS` file :)

**Comment by jsign** [comment]
I think both `AUTHORS` file and `Thank you` style are fine.
It can also have a direct link to [Github Contributors](https://github.com/prologic/bitcask/graphs/contributors) too.
