### ISSUE TITLE
Put() to use []byte byte slices (breaking API)

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#44]
Also off the back of #33 is the possibility of breaking the API (_while we still can!_) and change the signature of `Put()` from:

```#!go
func (b *Bitcask) Put(key string, value []byte) error
```

To:

```#!go
func (b *Bitcask) Put(key, value []byte) error
```

Apparently this is more flexible according to @awnumar and I see more implementations do this than don't. I _believe_ the only real concrete value this adds is the ability to then have keys that are non-ASCI.

**Comment by awnumar** [comment]
There's also the lower overhead since we read and write raw bytes to disk.

**Comment by prologic** [comment]
This poses an interesting problem; changint the signature is easy and all the affected places.

Changing the internals of the "keydir" (_mapping of keys to FileID + Offset_) however is another thing:

https://github.com/prologic/bitcask/blob/master/internal/keydir.go#L18-L21

I'm not sure how to handle this except to have a `map[uint64]Item` where `uint64` is a hash of the key.

**Comment by jsign** [comment]
I like the idea, but it raises one more question:
This would imply deleting the `Scan` API? (since can't make prefix searches with keys).

**Comment by prologic** [comment]
I've already been working on this and am about 3/4 the way there. I actually have properly forked trie now to use `[]byte` byte slices instead of `string` and internally serialization to byte slices. It should also ake trie faster. I can put up the branch if you want early access? But its unfinished.

**Comment by prologic** [comment]
WIP branches:

- https://github.com/prologic/bitcask/tree/put_byte_slice
- https://github.com/prologic/trie/tree/keys_as_byte_slices

**Comment by jsign** [comment]
Cool, take your time and when is complete I'll take a look and continue discussing from there. :+1:
