### ISSUE TITLE
Import/Export tool?

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#47]
With #42 landing soon it might become necessary to build two new sub-commands and tooling for the `bitcask` CLI to be able to support long-term backup and restore of a database. Since we're changing the on-disk format in #42 this _might_ become necessary for anyone upgrading from > [v0.3.1](https://github.com/prologic/bitcask/releases/tag/v0.3.1)

The main requirement here would be to pick a representation that is unlikely to change over time. It doesn't have to be super fast; but stable. I would expect the following to be possible:

```#!sh
$ bitcask -p ./my.db import < /path/to/dump
```

/cc @awnumar

**Comment by awnumar** [comment]
Interesting solution. In terms of a long term backup, maybe JSON?

**Comment by prologic** [comment]
Yeah I was thinking JSON too for portability. Basically just take the `Entry` struct and serialize it as JSON one per line so weo don't have to worry about loading it all up in meory (_which would likely explore_)
