### ISSUE TITLE
How large is too large?

### ISSUE THREAD

**Issue by rjasonadams** [prologic/bitcask#5]
Hello,

I have a project where we store ~12TB in the database. The average key size is ~128 bytes and the average value is around 600KB. Do you feel that your library would scale to this size?

**Comment by prologic** [comment]
Back of paper napkin math says this should be around ~12M datafiles.

You might want to increase the maximum datafile size with `WithMaxDatafileSize(...)` and make this 1GB -- That's around 12K datafiles.

The limitation here isn't Bitcask; it's your underlying file system. Also the design of the database itself (*similar to Riak*) should scale with any dataset sie linearly.

Let me know how you god!

**Comment by rjasonadams** [comment]
We're currently running with a db (BadgerDB) that's configured for ~256M data files. We're seeing around 30-40k files on xfs w/o issue. We have a reasonable amount of deletes, so I'm betting the merge operation would be quite heavy. ;) I like the simplicity of the bitcask design though.

 Do you have a rough idea of the memory required per key?

**Comment by prologic** [comment]
> We're currently running with a db (BadgerDB) that's configured for ~256M data files. We're seeing around 30-40k files on xfs w/o issue. We have a reasonable amount of deletes, so I'm betting the merge operation would be quite heavy. ;) I like the simplicity of the bitcask design though.

This should be fine. Re merges; I have chosen not to implement any automated merges here in this library or implicit magic there. Calling `.Merge()` is entirely up to you. It only conerves disk space and creates `.hint` files for faster process startup/restart -- Should not affect runtime performance; just Disk I/O as it dumps out the datafile to a temporary location and prunes old values and does an atomic rename.

> Do you have a rough idea of the memory required per key?

Yes!

What is held in memory is the size of the `Item` struct + size of your key(s). The overhead per key is roughly ~20 bytes per key.

**Comment by prologic** [comment]
Couple of other things to consider as well...

Given your dataset size and average key/value sizes. if you plan to import this data into a Bitcask database;  this will take around ~15-30mins (*depending on environment*) -- Bitcask benchmarks at around ~30k writes/s and ~400k reads/s

Another thing to consider is that the total number of datafiles you design (*depending on your configured datafile size*) also controls the number of open file descriptors. This is a design choice for performance reasons and a file pointer is held open per datafile so we don't constantly open/close datafiles on the read path. (*This could be configurable for much larger datasets where this is not desirable*). So for your dataset size with a max datafile size of ~500M expect to increase or set your `ulimit` to ~30k

**Comment by prologic** [comment]
I am closing this  now as it was a question. Feel free to open a new issue if you have any other questions related to Bitcask or find bugs or performance problems. Happy to help! Thanks for asking these questions too!

**Comment by prologic** [comment]
@rjasonadams Hey! Curious what you ended up doing here? if you chose another path that's fine! I'd love to hear feedback positive or negative. Thanks :D
