### ISSUE TITLE
Add a Sync() option for stronger durability (optional)

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#62]
This was discussed in #61 but is also a set of features I've wanted to add for a while. The capability for the user of Bitcask to set appropriate durability levels depending on their specific user-case and needs.

This is to track the progress and addition of a `Sync()` optional feature which would cause a `sync` on every `write` at the expensve of performance.

**Comment by awnumar** [comment]
This makes me wonder, how does bitcask perform with data corruption? For example, the process is interrupted mid-write, etc. Would the on-disk store ever be left in an inconsistent state?

Ideally I would say quasi-atomic writes are desirable.

**Comment by prologic** [comment]
Good question. We might have made it slightly worse with the new codec too as it has multiple write calls. AFAIK we haven't written code (yet?) to handle a corrupt data file. We probably should.

**Comment by awnumar** [comment]
What's the write ahead log used for? It can be repurposed to handle this also I think.

**Comment by prologic** [comment]
That's the entire design from the paper :) there is an active/current data file that is only append to and a number of inactive / rotated / merged datafiles we read from.
