### ISSUE TITLE
Very high RAM usage

### ISSUE THREAD

**Issue by awnumar** [prologic/bitcask#67]
My app is intending to write a total of around 3.6 GiB to the database. Keys are all 32 bytes long and values are all around 4 KiB.

```
[i] Encrypting 9 files from "test_data" (3.596GiB)
[?] Enter master key: ;
[i] Processing key...
[+] Sealing test_data/1k.data (1KiB)
[+] Sealing test_data/2m.data (2MiB)
[+] Sealing test_data/4k.data (4KiB)
[+] Sealing test_data/checksum.json (450B)
[+] Sealing test_data/folder/32m.data (32MiB)
[+] Sealing test_data/folder/64m.data (64MiB)
[+] Sealing test_data/folder/large/1g.data (1GiB)
[+] Sealing test_data/folder/large/2g.data (2GiB)
[+] Sealing test_data/folder/large/512m.data (512MiB)
[i] Syncing data with disk...
[i] Compacting database...
[1]    18243 killed     ./gravity seal test_data
```

That last line there where the process is killed during the `Merge` operation is due to the application using around 13 GB of RAM and being killed by the operating system. Before the merge operation, memory usage peaked at around 7-8 GB.

**Comment by awnumar** [comment]
Maybe a memory leak? It seems likely that the garbage collector did not run in the short interval where the application slurped up that much memory from the operating system.

If so, we can either re-use buffers where possible or manually run garbage collection.

**Comment by awnumar** [comment]
Okay this is unexpected.

![pprof001](https://user-images.githubusercontent.com/8942495/63057200-9f3ced00-bee1-11e9-9fe6-5784bdbc986a.png)

**Comment by prologic** [comment]
I was afraid of that :/ ITs the trie library that's eating up all the memory isn't it?

**Comment by awnumar** [comment]
Looks like it yes.

**Comment by prologic** [comment]
Perhaps its worth  filing an [issue](https://github.com/derekparker/trie/issues) against that project and maybe putting up a PR to fix it :)

**Comment by awnumar** [comment]
I opened an issue but it doesn't look like trie is really maintained.

**Comment by jsign** [comment]
I'm quite suspicious about a recent change that a user did in order to improve performance on a `collect` internal method, which implies saving the partial prefix path into the trie.

I'll do a small regression and report here if this may be the cause.

**Comment by jsign** [comment]
@awnumar , @prologic , I'm trying to reproduce this problem with a quick and dirty code.
Can you try to run [this](https://gist.github.com/jsign/6df2de9eb6ef7534744d4f95692fa771) with a `go.mod` to the tip of master of `bitcask`: `require github.com/prologic/bitcask v0.3.3-0.20190814105308-156d29e344a9`?

My results for `go tool pprof heap.out` doing a `web` command:
![image](https://user-images.githubusercontent.com/6136245/63066349-05c10b80-bee0-11e9-9e6d-a423c7e07780.png)

`totalVolumeSize` can be increased to match the original volume size of @awnumar , but now just trying confirm some results in a particular code.

**Comment by awnumar** [comment]
![profile001](https://user-images.githubusercontent.com/8942495/63084145-713bc500-bf42-11e9-81c2-e6f803220ee0.png)

**Comment by jsign** [comment]
I think that the `Node` data structure in the trie may be quite bloated. 
I'll throw some small analysis in the issue you created in that repo.

**Comment by awnumar** [comment]
Is `trie` only used for `Scan`? My application doesn't ever use that function so it seems strange for `Put` and `Get` to lift the burden of supporting it.

**Comment by jsign** [comment]
AFAIK, yes, only for `Scan`.

Maybe `Scan` support can be configurable with a variadic argument, making `Scan` (and thus `trie` usage) disabled by default. If someone needs `Scan`, let only them pay the mem and cpu cost of support it.

If we think this is a good idea, I have room to propose a PR. I guess the main discussion would be if disable it or not by default. I think disabled my be the best, and explain in the docs which is the impact of enabling it.

**Comment by awnumar** [comment]
Pushed some changes inspired by how the synced writes functionality works to the [`scan`](https://github.com/prologic/bitcask/tree/scan) branch: https://github.com/prologic/bitcask/commit/716b63c15c41f3fd63dd285a677e9f01cb380f43

Is this along the lines of what you were thinking? Feel free to modify

**Comment by awnumar** [comment]
New memory profiles in that branch:

Storing the data:

![profile001](https://user-images.githubusercontent.com/8942495/63103850-cb09b280-bf75-11e9-8458-e34293ccbdec.png)

Retrieving it:

![profile002](https://user-images.githubusercontent.com/8942495/63103864-d066fd00-bf75-11e9-8efe-d98f5193cd59.png)

**Comment by awnumar** [comment]
Without merge muddying the water: 
![profile001](https://user-images.githubusercontent.com/8942495/63104225-73b81200-bf76-11e9-907c-df1e99843920.png)

**Comment by jsign** [comment]
Yes, that was exactly the idea. I think this is a good change to merge.

**Comment by awnumar** [comment]
Came across [this](https://github.com/dghubble/trie) package that claims to have allocate nothing on the heap. I'm not sure if it's the same thing though.

**Comment by prologic** [comment]
Reopening because we still need to resolve this with either a replacement trie library, write our own or fix this goddamn memory leak bug :)

**Comment by prologic** [comment]
So I have no particular issue against disabling fast `.Scan()` for now; I think we should still fix this however. It is typical that a key value store have a way to do fast prefix or range scans of keys.

**Comment by jsign** [comment]
I took a quick look at this other Trie implementation, but it doesn't support doing operations similar to `PrefixScan`. Also, it assumes that Trie traversal is guided by slashes in the keys, e.g: a natural key for this library with form `one/two/three/hello` which I guess it makes sense for Routing applications in which Tries may save a lot of space compared to maps.

It also has a `walk` operation but is basically a depth-first traversal of the whole trie, so using this for Prefixes is inefficient.

As with anything, we can build on this library to see what's possible, e.g: instead of using slashes as key partitioning use an empty string + creating a new function to do a `PrefixScan` using the data structures of this library. It might take a little work...

**Comment by prologic** [comment]
So what are we doing here besides having an opt-out?

**Comment by prologic** [comment]
I've been giving this some thought over the past few days. Am wondering if we should just write our own trie that's more memory efficient and specific?

**Comment by prologic** [comment]
At first glance, [this library](https://github.com/alexanderbez/go-trie) looks to have a much more efficient implementation. Haven't tested it yet though.
