### ISSUE TITLE
WIP: File corruption handling

### ISSUE THREAD

**Issue by jsign** [prologic/bitcask#78]
There're no checks regarding data corruption detection or recovery.

I think most of the work involves not trusting read in the codecs:
- `size`s prefixes should be checked for reasonable bounds, if not `make(..., size)` might lead to out of memory.
- `offset`s should be reasonable regarding the file size.
- checksums?

Also, doing `ReadFull` may fail due to partial reads which is a sign of data corruption. A possible action is truncate the file up to the point of corruption to make a recovery. Maybe only doing this with a special flag for recovery to avoid unwanted effects. Let the user decide if do it on a next run with that flag.

**Comment by prologic** [comment]
Can we perhaps detect possible corruption and build a `bitcask recover` sub-command? Making it both a manual and user-decision?

**Comment by jsign** [comment]
I like the idea of using tooling for recovery. I could target this change and start making progress... can't be sure to make fast progress but can break the ice.

**Comment by prologic** [comment]
Sounds good to me! Even just a first cut of basic corruption detection and recovery will be a start :) We can always iterate.

**Comment by jsign** [comment]
I think we should also take the opportunity to do more tests while adding functionality, for the reasons we all know. Also, having low test coverage might be a downside to someone deciding to use bitcask.

Maybe I'll start adding, at least reasonable, tests to codecs in general and that might also help adding tests for corruption scenarios and keep going on from there. So, I'll start from the ground up with that direction in mind. I'll try to keep PRs short and clear to make review less exploding.

**Comment by jsign** [comment]
How do you imagine the `bitcask recovery` command API?

For example:
- `bitcask recovery db [path]` (with a default `--health` flag): Shows if the file is corrupted, it only reads.
- `bitcask recovery db --recover [path]`: Makes a `--health` and if corrupted tries to save the recovered file somewhere else. (Doesn't mutate the one in `path` to be safe).
- `bitcask recovery index [path]` (with a default `--health` flag): Same as before with index file.
- `bitcask recovery index --recover [path]`: Same as before with index file.
- use alias `recovery`, `recover`, `health`

Ideas?

**Comment by prologic** [comment]
A lot of the sub-commands of `bitcask` already take persistent global flags such as `-p/--path` as the path to the database. So... Reusing that would be good to keep things consistent.

`bitcask recover` is probably a better name for the new tool as it describe an action/verb. Thoughts?

I'm not convinced on the individual parts "recover full db" vs. "recover index" -- Why not just both in a single tool? If someone is fine just report it and skip? Also I think its more conventional to provide a `-n/--dry-run` flag (_a lot of UNIX tools do_) perhaps we can adopt this pattern too?

Examples:

```#!sh
$ bitcask -p /path/to/db recovery -n
$ echo $?
0
```

Everything is okay!

Similarly adding a `-d/--debug` flag would spit out more verbose output via `log.Debug()`?

Just some thoughts :)

**Comment by jsign** [comment]
Agree with all points.
We'll further iterate on the discussion in its respective PR, enough to progress now.

**Comment by jsign** [comment]
The next phase will be doing the analogous thing with the datafiles. So, moving in that direction next.

**Comment by jsign** [comment]
When #99 be merged, the last step is doing something about datafiles in the recovery tool to finish this epic.
