### ISSUE TITLE
read/write only sessions

### ISSUE THREAD

**Issue by awnumar** [prologic/bitcask#79]
A write-only (append only) session would only need to hold the handle to the current open file and would not need to store the keys in memory at all for fast retrieval, as there will be no retrieval. This would result in almost no ram usage, and it has the side benefit of preventing sessions from accessing previously stored data in the database.

A read-only mode would prevent the accidental mutation of previously stored elements, but would otherwise still use as much resources as a normal session. The only difference is the resource usage won't grow during the program's lifetime.

Any thoughts on this idea?

**Comment by prologic** [comment]
There are some things to consider here...

First off -- What would the use-case here be? Would you have a Writer-only service that only accepts inbound writes to the database? And subsequently a bunch of Read-only service(s) reading data?

One thing to consider is that we use a file lock to lock the database which we would have to change the semantics of to make a set of options/features like this work -- Like just locking the active log file from multiple writers (_readers are safe_).

**Comment by awnumar** [comment]
The only modification I propose is an option passed to Open. The session is the transient interval between opening the database and closing it. Perhaps functions could be added to switch between states also.

Use case is an application that is created, does some amount of work and exits. If it knows it doesn't need read access during this time, it doesn't have to then carry the burden of supporting it.

> One thing to consider is that we use a file lock to lock the database which we would have to change the semantics of to make a set of options/features like this work -- Like just locking the active log file from multiple writers (readers are safe).

Well spotted

**Comment by prologic** [comment]
> Use case is an application that is created, does some amount of work and exits. If it knows it doesn't need read access during this time, it doesn't have to then carry the burden of supporting it.

This is a good enough use-case for me! 👍

I'm not sure about switching states though -- That _could_ get complicated implementation-wise but we'll see :) (_code wins arguments!_)

**Comment by awnumar** [comment]
> I'm not sure about switching states though -- That could get complicated implementation-wise but we'll see :) (code wins arguments!)

To be fair I don't think there's much need for it. The caller should open the database normally in that case.

**Comment by prologic** [comment]
Agreed :) So this all sounds fine. Are you going to write the PR? :)

It would also be nice to apply similar options to the CLI `bitcask` too (_mostly useful in shell scripts, etc_)

**Comment by awnumar** [comment]
I'll get started on it later this week.

**Comment by prologic** [comment]
@jsign Just FYI many of the benchmark test suits are failing with:

```
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-4         	--- FAIL: BenchmarkGet/128B-4
    bitcask_test.go:539: data size too large
BenchmarkGet/256B-4         	--- FAIL: BenchmarkGet/256B-4
    bitcask_test.go:539: data size too large
BenchmarkGet/512B-4         	--- FAIL: BenchmarkGet/512B-4
    bitcask_test.go:539: data size too large
BenchmarkGet/1K-4           	--- FAIL: BenchmarkGet/1K-4
    bitcask_test.go:539: data size too large
BenchmarkGet/2K-4           	--- FAIL: BenchmarkGet/2K-4
    bitcask_test.go:539: data size too large
BenchmarkGet/4K-4           	--- FAIL: BenchmarkGet/4K-4
    bitcask_test.go:539: data size too large
BenchmarkGet/8K-4           	--- FAIL: BenchmarkGet/8K-4
    bitcask_test.go:539: data size too large
BenchmarkGet/16K-4          	--- FAIL: BenchmarkGet/16K-4
    bitcask_test.go:539: data size too large
BenchmarkGet/32K-4          	--- FAIL: BenchmarkGet/32K-4
    bitcask_test.go:539: data size too large
--- FAIL: BenchmarkGet
```

Not sure if you're aware?

**Comment by awnumar** [comment]
Pushed some initial changes to the `mode` branch implementing an append-only mode. After seeing the considerable breaking changes induced and how much of the API relies on having the keys in memory, I'm reconsidering if this is worth it. What do you think?

**Comment by prologic** [comment]
Well... `Bitcask.trie` is actually an interface. `art.Tree` is an interface type. So you _could_ stub  it out?

**Comment by prologic** [comment]
For example if you know you're never going to need to search the key/value data at all; replace `b.trie` with an empty implementation.

**Comment by awnumar** [comment]
Yep that was what I was going for.

**Comment by prologic** [comment]
Are you still working on this? I have reasons to add a `--read-only` flag and `WithReadOnly()` option so I can do things like; attach a graphical web ui to an existing bitcask db; or a curses/tui.

**Comment by awnumar** [comment]
No I think I will close this.

1. Read-only option can be handled at the higher-level application level. A nice way of doing so is to expose the database through an interface that has no write methods. There's no memory benefits to be gained using this option.
2. A write-only option had the potential to reap the benefits of not having to store the keys in memory. However memory usage has decreased a lot recently and the feature requires lots of changes to the API.

I think at this point it adds too much complexity for relatively little benefits.
