### ISSUE TITLE
readConfig unused?

### ISSUE THREAD

**Issue by jsign** [prologic/bitcask#85]
If the database is open without options flags, isn't the idea to read an existant `config.json`?
If I'm not missing something `bitcask.readConfig` is unused?

**Comment by prologic** [comment]
That was the intention yes. Bug?

**Comment by jsign** [comment]
It seems so. If you can confirm it, maybe tag this as bug :)

**Comment by prologic** [comment]
Looks like that method is just completely unused. I used `getConfig(...)` instead in `options.go` which has the correct behaviour. I must have forgotten to remove the other func?
