### ISSUE TITLE
Data races

### ISSUE THREAD

**Issue by jsign** [prologic/bitcask#93]
Reading the code in data-race mode mindset, I think there're some problems. Before making any PR, I'd like to mention them here to double-check with second eyes.

First, take a look at function `.Put`. In this function call, there're two mutually exclusive sections which are mutexed: `b.put(..)` (mutex is used inside `.put`) and `b.trie.Insert(..)`. If that doesn't seem odd yet consider the following: `b.put()` is executed completely and mutex is thus released. Just before reaching the trie insert, a `.Delete` call is completely executed. Afterward, the `b.trie.Insert()` is done. At this state the datafile has _tombstoned_ the key, but the trie has it active.  Of course, other similar things can happen depending on the execution order of things.

Also, take a look at `.Get()`. Only the `.Search()` is read-mutexed. At this point, I think many bad things can happen. Thinking about `b.cur` is unprotected from concurrent `b.Put()`s that might generate new a new current file if the actual is in the size limit. This may lead to multiple consequences. Also, consider that the `Search` found the key, but concurrently is deleted before doing `.ReadAt`.

Of course, solving this seems quite easy. But I'm quite surprised about this many things, so I'm kind of doubting I'm missing something here.

**Comment by prologic** [comment]
Nope I think your correct! Just missed!

 Is this something that we can improve the concurrency unit tests to catch?
-- 

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by jsign** [comment]
We could generate a test that concurrently Put and Delete for some time, and make a copy of the resulting tree. Then check if reopening the datafile will exactly match the saved tree.

Later I'll make a PR to fix this and give a chance to this test idea to see if catches the current situation.

**Comment by jsign** [comment]
May have other options too. I'll target this after the pending PR that made some file movements.
